Repository Kernel360/KBE5_HALO_FE, pull requests merged in 2025-07, with the labels that each got.

#131 [Refactor] 관리자 페이지에서 추가된 페이지를 index.tsx에 추가
  src/router/index.tsx
Labels: 🔧 refactor

#133 [Refactor] 수요자 리뷰 페이지 api 연결
  src/features/customer/api/CustomerReview.ts
  src/features/customer/components/CustomerHeader.tsx
  src/features/customer/pages/customerReview/CustomerReviewForm.tsx
  src/features/customer/pages/customerReview/CustomerReviewsPage.tsx
Labels: 🔧 refactor

#141 [refactor] 문의사항 개선
  src/features/admin/api/adminInquiry.ts
  src/features/admin/components/AdminPagination.tsx
  src/features/admin/components/TableSection.tsx
  src/features/admin/pages/AdminInquiry/AdminInquiries.tsx
  src/features/admin/pages/AdminInquiry/AdminInquiryDetail.tsx
  src/features/admin/pages/AdminMain.tsx
  src/features/admin/types/AdminInquiryType.ts
  src/features/admin/types/AdminInquirylType.ts
  src/features/customer/api/CustomerInquiries.ts
  src/features/customer/pages/customerInquiry/CustomerInquiryDetail.tsx
  src/features/customer/pages/customerInquiry/CustomerInquiryForm.tsx
  src/features/customer/pages/customerInquiry/CustomerInquiryPage.tsx
  src/features/customer/types/CustomerInquiryType.ts
  src/features/manager/api/managerInquiry.ts
  src/features/manager/components/ManagerSidebar.tsx
  src/features/manager/pages/ManagerInquiry/ManagerInquiries.tsx
  src/features/manager/pages/ManagerInquiry/ManagerInquiryDetail.tsx
  src/features/manager/pages/ManagerInquiry/ManagerInquiryForm.tsx
  src/features/manager/types/ManagerInquirylType.ts
  src/router/index.tsx
  src/shared/components/Pagination.tsx
  src/shared/components/ui/ResetButton.tsx
  src/shared/components/ui/SearchButton.tsx
  src/shared/types/InquiryType.ts
Labels: 🔧 refactor

#146 [Fix] 빌드 애러 수정
  src/features/manager/api/managerMy.ts
  src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
  src/features/manager/pages/ManagerSignup.tsx
Labels: ⚠️ bug

#152 [Dev] 매니저 지원 오류 수정
  src/features/manager/pages/ManagerSignup.tsx
Labels: ⚠️ bug

#162 [Refactor] 매니저 예약 페이지 리펙토링
  src/features/admin/api/adminAuth.ts
  src/features/admin/api/adminInquiry.ts
  src/features/admin/components/ManagerAddressMap.tsx
  src/features/admin/pages/AdminCustomer/AdminCustomers.tsx
  src/features/manager/api/managerReservation.ts
  src/features/manager/components/CheckInOutCard.tsx
  src/features/manager/components/ManagerCleaningLogModal.tsx
  src/features/manager/components/MangerServiceCheckLogModal.tsx
  src/features/manager/components/ReservationCheckInOutBanner.tsx
  src/features/manager/components/ReservationRequestBanner.tsx
  src/features/manager/components/TodayScheduleSection.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
  src/shared/components/FileUploadSection.tsx
  src/shared/utils/dateUtils.ts
  src/shared/utils/fileUpload.ts
  src/shared/utils/login.ts
Labels: 🔧 refactor

#164 [Refactor] 매니저 예약 상세 페이지 개선
  src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
Labels: 🔧 refactor

#165 [Refactor] 매니저 페이지 카카오맵 연동
  index.html
  src/features/manager/components/AddressMapCard.tsx
  src/features/manager/pages/ManagerMy/ManagerMy.tsx
  src/shared/components/AddressSearch.tsx
Labels: 🔧 refactor

#173 [Refactor] 카카오 주소 불러오기 수정
  index.html
  src/features/customer/pages/CustomerLogin.tsx
  src/features/customer/pages/CustomerMyInfo.tsx
  src/features/customer/pages/CustomerSignup.tsx
  src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
  src/features/manager/pages/ManagerSignup.tsx
  src/shared/components/AddressSearch.tsx
  src/shared/components/ui/BirthDateCalendar.tsx
  src/store/useAddressStore.ts
Labels: 🔧 refactor

#174 [Refactor] 카카오 주소 불러오기 수정
  index.html
  src/features/customer/pages/CustomerLogin.tsx
  src/features/customer/pages/CustomerMyInfo.tsx
  src/features/customer/pages/CustomerSignup.tsx
  src/features/customer/pages/reservation/ReservationStepOne.tsx
  src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
  src/features/manager/pages/ManagerSignup.tsx
  src/shared/components/AddressSearch.tsx
  src/shared/components/ui/BirthDateCalendar.tsx
  src/store/useAddressStore.ts
Labels: 🔧 refactor

#177 [Refactor] 헤더, 푸터, 홈페이지 개선
  src/features/customer/components/CustomerFooter.tsx
  src/features/customer/components/CustomerHeader.tsx
  src/features/customer/modal/ServiceDetailModal.tsx
  src/features/customer/pages/CustomerMain.tsx
Labels: 🔧 refactor

#179 refactor : 수요자 마이페이지 개선
  src/features/customer/pages/CustomerMyInfo.tsx
Labels: 🔧 refactor

#183 [Fix] 빌드 오류 수정 및 페이지 권한 없는 사용자 로그인 가능 문제
  src/features/admin/pages/AdminAccount/AdminAccounts.tsx
  src/features/customer/pages/CustomerLogin.tsx
  src/features/customer/pages/CustomerSignup.tsx
  src/features/manager/api/managerAuth.ts
  src/features/manager/pages/ManagerSignup.tsx
  src/features/manager/types/ManagerAuthType.ts
  src/main.tsx
  src/shared/components/OAuthFailPage.tsx
  src/shared/components/OAuthProgressPage.tsx
  src/shared/components/OAuthSuccessPage.tsx
  src/shared/components/ui/LoginCard.tsx
  src/shared/utils/login.ts
  src/shared/utils/logout.ts
Labels: ⚠️ bug

#185 [Feature] 매니저, 관리자 정산 페이지 개발
  src/features/admin/api/adminSettlement.ts
  src/features/admin/components/AdminSidebar.tsx
  src/features/admin/pages/AdminMain.tsx
  src/features/admin/pages/AdminSettlement/AdminSettlements.tsx
  src/features/admin/types/AdminPaymentType.ts
  src/features/manager/api/managerPayment.ts
  src/features/manager/components/KPISection.tsx
  src/features/manager/components/ManagerSidebar.tsx
  src/features/manager/components/TodayScheduleSection.tsx
  src/features/manager/pages/ManagerMain.tsx
  src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
  src/features/manager/types/ManagerPaymentType.ts
  src/router/index.tsx
Labels: 🔨 feature

#186 소셜로그인, 정산, 관리자 계정 수정
  src/features/admin/api/adminSettlement.ts
  src/features/admin/components/AdminAccountForm.tsx
  src/features/admin/components/AdminSidebar.tsx
  src/features/admin/pages/AdminAccount/AdminAccountForm.tsx
  src/features/admin/pages/AdminAccount/AdminAccounts.tsx
  src/features/admin/pages/AdminLogin.tsx
  src/features/admin/pages/AdminMain.tsx
  src/features/admin/pages/AdminSettlement/AdminSettlements.tsx
  src/features/admin/types/AdminPaymentType.ts
  src/features/customer/api/customerAuth.ts
  src/features/customer/pages/CustomerLogin.tsx
  src/features/customer/pages/CustomerSignup.tsx
  src/features/customer/types/CustomerSignupType.ts
  src/features/manager/api/managerAuth.ts
  src/features/manager/api/managerPayment.ts
  src/features/manager/components/KPISection.tsx
  src/features/manager/components/ManagerSidebar.tsx
  src/features/manager/components/TodayScheduleSection.tsx
  src/features/manager/pages/ManagerLogin.tsx
  src/features/manager/pages/ManagerMain.tsx
  src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
  src/features/manager/pages/ManagerSignup.tsx
  src/features/manager/types/ManagerAuthType.ts
  src/features/manager/types/ManagerPaymentType.ts
  src/router/index.tsx
  src/services/axios.ts
  src/shared/components/OAuthFailPage.tsx
  src/shared/components/OAuthProgressPage.tsx
  src/shared/components/OAuthSuccessPage.tsx
  src/shared/components/ui/FeatureCard.tsx
  src/shared/components/ui/FormField.tsx
  src/shared/components/ui/GoogleLoginButton.tsx
  src/shared/components/ui/LoginCard.tsx
  src/shared/utils/googleOAuth.ts
  src/shared/utils/login.ts
  src/shared/utils/logout.ts
  src/store/useUserStore.ts
Labels: 🔨 feature, 🔧 refactor

#189 refactor: 빌드에러 수정
  src/features/customer/pages/reservation/CustomerMyReservationDetail.tsx
Labels: 🔧 refactor

#190 [Refactor] 수요자페이지 개선
  src/assets/office.png
  src/features/customer/modal/CustomerReviewModal.tsx
  src/features/customer/pages/CustomerMain.tsx
  src/features/customer/pages/customerReview/CustomerReviewsPage.tsx
  src/features/customer/pages/reservation/CustomerMyReservationDetail.tsx
  src/features/customer/pages/reservation/CustomerMyReservationPage.tsx
  src/features/customer/types/CustomerReviewType.ts
Labels: 🔧 refactor

#192 [Refactor] 관리자 페이지 리펙토링
  package-lock.json
  package.json
  src/features/admin/api/adminCustomer.ts
  src/features/admin/api/adminInquiry.ts
  src/features/admin/api/adminManager.ts
  src/features/admin/api/adminReservation.ts
  src/features/admin/components/AdminAccountMobileCard.tsx
  src/features/admin/components/AdminSearchForm.tsx
  src/features/admin/components/AdminSidebar.tsx
  src/features/admin/components/AdminTable.tsx
  src/features/admin/components/ManagerAvailableTimeBar.tsx
  src/features/admin/components/ManagerAvailableTimeClock.tsx
  src/features/admin/components/ManagerAvailableTimeTable.tsx
  src/features/admin/components/ManagerContractInfo.tsx
  src/features/admin/components/ManagerDetailInfo.tsx
  src/features/admin/components/ManagerProfileSummaryCard.tsx
  src/features/admin/components/RecentInquiriesCard.tsx
  src/features/admin/components/RecentReviewsCard.tsx
  src/features/admin/pages/AdminAccount/AdminAccounts.tsx
  src/features/admin/pages/AdminBanner/AdminBanneerForm.tsx
  src/features/admin/pages/AdminCustomer/AdminCustomerDetail.tsx
  src/features/admin/pages/AdminCustomer/AdminCustomers.tsx
  src/features/admin/pages/AdminInquiry/AdminInquiries.tsx
  src/features/admin/pages/AdminMain.tsx
  src/features/admin/pages/AdminManager/AdminManagerDetail.tsx
  src/features/admin/pages/AdminManager/AdminManagers.tsx
  src/features/admin/pages/AdminReservation/AdminReservationDetail.tsx
  src/features/admin/pages/AdminReservation/AdminReservations.tsx
  src/features/admin/types/AdminInquiryType.ts
  src/features/admin/types/AdminManagerType.ts
  src/features/admin/types/AdminReservationType.ts
  src/features/manager/components/AddressMapCard.tsx
  src/features/manager/pages/ManagerMy/ManagerMy.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
  src/main.tsx
  src/shared/components/OAuthProgressPage.tsx
  src/shared/components/ui/Badge.tsx
  src/shared/components/ui/ReviewCard.tsx
  src/shared/utils/dateUtils.ts
Labels: 🔧 refactor

#195 Dev
  package-lock.json
  package.json
  src/features/admin/api/adminCustomer.ts
  src/features/admin/api/adminInquiry.ts
  src/features/admin/api/adminManager.ts
  src/features/admin/api/adminReservation.ts
  src/features/admin/components/AdminAccountMobileCard.tsx
  src/features/admin/components/AdminSearchForm.tsx
  src/features/admin/components/AdminSidebar.tsx
  src/features/admin/components/AdminTable.tsx
  src/features/admin/components/ManagerAvailableTimeBar.tsx
  src/features/admin/components/ManagerAvailableTimeClock.tsx
  src/features/admin/components/ManagerAvailableTimeTable.tsx
  src/features/admin/components/ManagerContractInfo.tsx
  src/features/admin/components/ManagerDetailInfo.tsx
  src/features/admin/components/ManagerProfileSummaryCard.tsx
  src/features/admin/components/RecentInquiriesCard.tsx
  src/features/admin/components/RecentReviewsCard.tsx
  src/features/admin/pages/AdminAccount/AdminAccounts.tsx
  src/features/admin/pages/AdminBanner/AdminBanneerForm.tsx
  src/features/admin/pages/AdminCustomer/AdminCustomerDetail.tsx
  src/features/admin/pages/AdminCustomer/AdminCustomers.tsx
  src/features/admin/pages/AdminInquiry/AdminInquiries.tsx
  src/features/admin/pages/AdminMain.tsx
  src/features/admin/pages/AdminManager/AdminManagerDetail.tsx
  src/features/admin/pages/AdminManager/AdminManagers.tsx
  src/features/admin/pages/AdminReservation/AdminReservationDetail.tsx
  src/features/admin/pages/AdminReservation/AdminReservations.tsx
  src/features/admin/types/AdminInquiryType.ts
  src/features/admin/types/AdminManagerType.ts
  src/features/admin/types/AdminReservationType.ts
  src/features/customer/api/CustomerReservation.ts
  src/features/customer/components/CustomerSidebar.tsx
  src/features/customer/components/search/ReservationSearchFilter.tsx
  src/features/customer/pages/reservation/CustomerMyReservationPage.tsx
  src/features/customer/types/CustomerReservationType.ts
  src/features/manager/components/AddressMapCard.tsx
  src/features/manager/pages/ManagerMy/ManagerMy.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
  src/shared/components/OAuthProgressPage.tsx
  src/shared/components/ui/Badge.tsx
  src/shared/components/ui/ReviewCard.tsx
  src/shared/utils/dateUtils.ts
  src/types/kakao.d.ts
Labels: 🔧 refactor

#197 [Refactor] 매니저 페이지 리펙토링
  src/features/manager/components/CheckInOutCard.tsx
  src/features/manager/components/KPISection.tsx
  src/features/manager/components/ManagerReservationSearchForm.tsx
  src/features/manager/components/ManagerReservationTable.tsx
  src/features/manager/components/ReservationCheckInOutBanner.tsx
  src/features/manager/pages/ManagerMy/ManagerMy.tsx
  src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
  src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservations.tsx
  src/features/manager/pages/ManagerReview/ManagerReviews.tsx
  src/features/manager/types/ManagerMyType.ts
  src/features/manager/types/ManagerReservationType.ts
  src/shared/components/SearchForm.tsx
Labels: 🔧 refactor

#199 [Refactor] 매니저 페이지 리펙토링
  src/features/manager/components/CheckInOutCard.tsx
  src/features/manager/components/KPISection.tsx
  src/features/manager/components/ManagerReservationSearchForm.tsx
  src/features/manager/components/ManagerReservationTable.tsx
  src/features/manager/components/ReservationCheckInOutBanner.tsx
  src/features/manager/pages/ManagerInquiry/ManagerInquiries.tsx
  src/features/manager/pages/ManagerMy/ManagerMy.tsx
  src/features/manager/pages/ManagerMy/ManagerMyForm.tsx
  src/features/manager/pages/ManagerPayment/ManagerPayments.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservationDetail.tsx
  src/features/manager/pages/ManagerReservation/ManagerReservations.tsx
  src/features/manager/pages/ManagerReview/ManagerReviews.tsx
  src/features/manager/types/ManagerMyType.ts
  src/features/manager/types/ManagerReservationType.ts
  src/shared/components/SearchForm.tsx
Labels: 🔧 refactor

#200 [Refactor] 서비스 약관, 개인정보처리방침 페이지 추가
  src/features/admin/components/AdminAccountForm.tsx
  src/features/customer/components/CustomerFooter.tsx
  src/router/index.tsx
  src/shared/components/OAuthProgressPage.tsx
  src/shared/components/PrivacyPolicyPage.tsx
  src/shared/components/TermsOfServicePage.tsx
Labels: 🔧 refactor

#201 [Refactor] 서비스 약관, 개인정보처리방침 페이지 추가
  src/features/admin/components/AdminAccountForm.tsx
  src/features/customer/components/CustomerFooter.tsx
  src/router/index.tsx
  src/shared/components/OAuthProgressPage.tsx
  src/shared/components/PrivacyPolicyPage.tsx
  src/shared/components/TermsOfServicePage.tsx
Labels: 🔧 refactor

#204 [Fix] 소셜 로그인 신규 사용자 가입 오류 수정
  src/shared/components/OAuthProgressPage.tsx
Labels: ⚠️ bug

#207 [Feature] README 작성
  README.md
Labels: 🔨 feature
